config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
 
 resources:team
 
 resources:author
 
 resources:contact

 resources:city

 resources:user

 resources :sessions, only: [:new, :create, :destroy]

 resources :like 

 resources :gossip do
  resources :like
  resources :comment
  get :display
 end
 
  

get '/', to: 'gossip#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content,
	  presence: true
    belongs_to :user
    belongs_to :gossip		
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { minimum: 3, wrong_length: "3 to 14 characters is allowed" }
	validates :content,
	  presence: true

	belongs_to :user
	has_many :join_tag_gossips
	has_many :tags, through: :join_tag_gossips
	has_many :comments
	has_many :likes


end

app/models/join_pm.rb
class JoinPm < ApplicationRecord
	belongs_to :user
	belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :user
    has_many :join_pms
    
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_tag_gossips
	has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,
      presence: true, #tjr rempli
      uniqueness: true,  #unique
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } 
    validates :first_name,
      presence: true
    validates :last_name,
      presence: true
    validates :description,
      presence: true
    validates :age,
      presence: true,
	  numericality: { only_integer: true, greater_than_or_equal_to: 1}
    

	belongs_to :city
	has_many :gossips
	has_many :private_messages
	has_many :join_pms
	has_many :comments
	has_many :likes
	has_secure_password
 
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    def new
    end

    def create
    end

    def show
    end

    def index
    end

    def edit
    end

    def update
    end

    def destroy
    end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
    def new
        @comment = Comment.new
    end

    def create

         @comment = Comment.new(content: params['content'], gossip_id:params['gossip_id'],user_id:current_user.id)
            if @comment.save
                flash[:success] = "Le commentaire a été enregistré"
                render 'index/new'
            else
                flash[:error] = "Commentaire invalide"
                redirect_to gossip_index_path
            end
     end

    def show
    end

    def index
        @comments = gossip.comments
        @gossip = Gossip.find(params[:gossip_id])
    end

    def edit
    end

    def update
    end

    def destroy
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  include SessionsHelper

    def bootstrap_class_for flash_type
        { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
      end
    
      def flash_messages(opts = {})
        flash.each do |msg_type, message|
          concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
                  concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                  concat message 
                end)
        end
        nil
      end
    
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper

    def log_in(user)
        session[:user_id] = user.id
      end
end

app/views/comment/_comments.html.erb
<% @comment = Comment.all %>
<% params[:controller] = 'comment' %>
<% params[:action] = 'create' %>

<%  Comment.where(gossip_id:params[:id]).each do |comment| %>
    <%= comment.content %>
        
<%end%>


<%= render partial: 'comment/form' %>

app/views/comment/_form.html.erb
<div 
<input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >

</div>

  <div class="container">
    <h1> Poste un commentaire !</h1>
    <%= form_with url: gossip_comment_index_path(params[:id]) do %>
      <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
      <input type="hidden" name="gossip_id" value= @gossip.id >  
      <br /> 
     
        <%= text_field_tag 'content' %>
        <%= label_tag 'Ton commentaire' %>
  
      <br /> 
    
      <%= submit_tag "Valider", class: 'btn btn-primary btn-lg btn-submit col-4'  %>
    <% end %>
  </div>
</body>
</html>



<%= flash_messages %>

     <%= yield %>
   </div><!-- /container -->

app/views/comment/index.html.erb
<h1>Tous les commentaires sur le gossip <%= @gossip.title %></h1>


<% @comment.each do |comment |%>

    <%= comment.content %>

    <%end%>

<%= flash_messages %>

     <%= yield %>
   </div><!-- /container -->

app/views/comment/new.html.erb
<html>
<body>


<div class="container">
    
<%= flash_messages %>

<%= yield %>
</div><!-- /container -->


<div 
<input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >


</div>


  <div class="container">
    <h1> Poste un commentaire !</h1>
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
      <input type="hidden" name="gossip_id" value= params['gossip_id'] >  
      <br /> 
     
        <%= text_field_tag 'content' %>
        <%= label_tag 'Ton commentaire' %>
  
      <br /> 
    
      <%= submit_tag "Valider", class: 'btn btn-primary btn-lg btn-submit col-4'  %>
    <% end %>
  </div>
</body>
</html>

app/views/comment/show.html.erb
<h1>Hello</h1>


<%= @comment.content %>

<%= flash_messages %>

     <%= yield %>
   </div><!-- /container -->