config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
 
 resources:team
 
 resources:author
 
 resources:contact

 resources:city

 resources:user

 resources :sessions, only: [:new, :create, :destroy]

 resources :like 

 resources :gossip do
  resources :like
  resources :comment
  get :display
 end
 
  

get '/', to: 'gossip#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content,
	  presence: true
    belongs_to :user
    belongs_to :gossip		
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { minimum: 3, wrong_length: "3 to 14 characters is allowed" }
	validates :content,
	  presence: true

	belongs_to :user
	has_many :join_tag_gossips
	has_many :tags, through: :join_tag_gossips
	has_many :comments
	has_many :likes


end

app/models/join_pm.rb
class JoinPm < ApplicationRecord
	belongs_to :user
	belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :user
    has_many :join_pms
    
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_tag_gossips
	has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,
      presence: true, #tjr rempli
      uniqueness: true,  #unique
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } 
    validates :first_name,
      presence: true
    validates :last_name,
      presence: true
    validates :description,
      presence: true
    validates :age,
      presence: true,
	  numericality: { only_integer: true, greater_than_or_equal_to: 1}
    

	belongs_to :city
	has_many :gossips
	has_many :private_messages
	has_many :join_pms
	has_many :comments
	has_many :likes
	has_secure_password
 
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper

    def log_in(user)
        session[:user_id] = user.id
      end
end

app/views/dynamic_pages/gossip.html.erb
<p> <%= Gossip.find(@id).user.first_name %>  </p>
<br>
<%= link_to "Lien vers la fiche de l'auteur", author_path  %> <br>
<br>
<p> Le titre de ce gossip est : <%= Gossip.find(@id).title %> </p>
<br>
<p> Le contenu du gossip est : <%= Gossip.find(@id).content %> </p>
<br>
<p> Il a été créé le : <%= Gossip.find(@id).created_at %> </p>

app/views/dynamic_pages/id.html.erb
<h1> BIENVENUE  <%=@id%>! Ici c'est notre super site de potins, il est chouette, non ? </h1> <br>

<div class="card-columns"> 


<p><% Gossip.all.each do |gossip| %>
    

  <div class="card border-primary mb-3">
  <div class="card-header">
   Potin n°<%= gossip.id %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= gossip.title %>  </p>
    <footer class="blockquote-footer"><%= gossip.user.first_name %> </br> </br> </cite></footer>
    <a class="btn btn-secondary" <%= link_to 'Lien vers le gossip',gossip_path(gossip.id) %> 
  </div>
  <div class="card-footer">
    </div>
</div> 






    <% end %></p>
</div>  

     


    