config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
 
 resources:team
 
 resources:author
 
 resources:contact

 resources:city

 resources:user

 resources :sessions, only: [:new, :create, :destroy]

 resources :like 

 resources :gossip do
  resources :like
  resources :comment
  get :display
 end
 
  

get '/', to: 'gossip#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content,
	  presence: true
    belongs_to :user
    belongs_to :gossip		
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { minimum: 3, wrong_length: "3 to 14 characters is allowed" }
	validates :content,
	  presence: true

	belongs_to :user
	has_many :join_tag_gossips
	has_many :tags, through: :join_tag_gossips
	has_many :comments
	has_many :likes


end

app/models/join_pm.rb
class JoinPm < ApplicationRecord
	belongs_to :user
	belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :user
    has_many :join_pms
    
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_tag_gossips
	has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,
      presence: true, #tjr rempli
      uniqueness: true,  #unique
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } 
    validates :first_name,
      presence: true
    validates :last_name,
      presence: true
    validates :description,
      presence: true
    validates :age,
      presence: true,
	  numericality: { only_integer: true, greater_than_or_equal_to: 1}
    

	belongs_to :city
	has_many :gossips
	has_many :private_messages
	has_many :join_pms
	has_many :comments
	has_many :likes
	has_secure_password
 
end

app/controllers/city_controller.rb
class CityController < ApplicationController
    def new
    end

    def create
    end

    def show
    end

    def index
    end

    def edit
    end

    def update
    end

    def destroy
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
   before_action :authenticate_user, only: [:new,:show]
   before_action :user_is_author, only: [:edit,:destroy,:update]
   
    def new
      @gossip = Gossip.new
      
    end

    def create
      
       @gossip= Gossip.new(title: params['gossip_title'],content:params['gossip_content'], user: User.find_by(id: session[:user_id]))

       if @gossip.save
        flash.now[:success] = "Le gossip a été enregistré"
        render 'gossip/index', to: 'gossip#index'
        
       else
      flash.now[:error] = "Veuillez rentrer un titre (de plus de 3 caractères) et un contenu pour votre potin"
    	render 'gossip/new' 
       end

    end
    

    def show
       @my_gossip = Gossip.find(params[:id])
       @x = @my_gossip
       @my_city = City.find(@my_gossip.user.city_id) 
       @gossip = {id: @my_gossip.id, author: @my_gossip.user.first_name, title: @my_gossip.title, user_id: @my_gossip.user.id, content: @my_gossip.content, created_at: @my_gossip.created_at, city: @my_city.name}
       @gossip_comments = @my_gossip.comments
       @gossip_comment = Comment.new
      
    
    end

    def index
      @gossip= Gossip.all
       
    end

    def edit
      @gossip = Gossip.find(params[:id])
    end

    def update
   
      if @gossip.update(title: params['gossip_title'],content: params['gossip_content'])
         flash[:success] = "Le gossip a été modifié"
         redirect_to @gossip

      else
         flash.now[:error] = "Veuillez rentrer un titre (de plus de 3 caractères) et un contenu pour votre potin"
         render :edit
        
      end
    end

    def destroy
      @gossip.destroy
      flash[:notice] = "Le gossip a été détruit"
      redirect_to gossip_index_url
       end



       def display
         @products = Product.all
       end

       private

       def authenticate_user
         unless current_user
           flash.now[:danger] = "Please log in."
           redirect_to new_session_path
         end
       end

       def user_is_author
         @gossip = Gossip.find(params[:id])
         unless current_user == @gossip.user
            flash.now[:danger] = "Vous ne pouvez modifier que vos potins."
            redirect_to gossip_path(@gossip.id)
         end
      end



end

app/helpers/application_helper.rb
module ApplicationHelper
  
  include SessionsHelper

    def bootstrap_class_for flash_type
        { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
      end
    
      def flash_messages(opts = {})
        flash.each do |msg_type, message|
          concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
                  concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
                  concat message 
                end)
        end
        nil
      end
    
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper

    def log_in(user)
        session[:user_id] = user.id
      end
end

app/views/gossip/edit.html.erb
<div class="container">
      
<%= flash_messages %>

<%= yield %>
</div><!-- /container -->


<div 
<input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >


</div>

    <div class="container">
      <h1> Modifie ton potin !</h1>
      <%= form_tag url_for(action: 'update'), method: "PATCH" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <br /> 
       
          <%= text_field_tag 'gossip_title' ,value= Gossip.find(params[:id]).title %>
          <%= label_tag 'Le titre' %>
    
        <br /> 
        
          <%= text_field_tag 'gossip_content', value= Gossip.find(params[:id]).content%>
          <%= label_tag 'Dis nous tout' %>
        
        <br /> <br />
        <%= submit_tag "Valider", class: 'btn btn-primary btn-lg btn-submit col-4'  %>
      <% end %>
    </div>
  </body>
</html>

app/views/gossip/index.html.erb
<html>

<body>
     <div class="container">
      
     <%= flash_messages %>

     <%= yield %>
   </div><!-- /container -->

   <h1>   <span class="badge badge-secondary">The Gossip Project</span>Le site de gossip de THP</h1>

<% if current_user %>
<button type="button" class="btn btn-dark" style="margin-bottom:10px;">

<a <%= link_to 'Clique ici pour créer un nouveau potin',new_gossip_path %> </a>

</button>

<%end%>


<div class="row"> 


<p><% Gossip.all.each do |gossip| %>
    

  <div class="card border-dark mb-3 mx-3 col-lg-3">
  <div class="card-header">
   Gossip n°<%= gossip.id %>
   <%= render 'like/like' %>
  </div>
  <div class="card-body bg-light">
    <p class="card-text "><%= gossip.title %>  </p>
    <footer class="blockquote-footer"><%= gossip.user.first_name %> </br> </br> </cite></footer>
    <a class="btn btn-dark" <%= link_to 'Lien vers le gossip',gossip_path(gossip.id) %> 
  </div>
  <div class="card-footer">
    </div>
</div> 






    <% end %></p>
</div>  

</body>
</html>

     


    

app/views/gossip/new.html.erb
<html>
  <body>


  <div class="container">
      
  <%= flash_messages %>

  <%= yield %>
</div><!-- /container -->
  
    <div class="container">
      <h1> Créer ton nouveau potin !</h1>
      <%= form_tag url_for(action: 'create'), method: "post" do %>
        <input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
        <br /> 
       
          <%= text_field_tag 'gossip_title' %>
          <%= label_tag 'Le titre' %>
    
        <br /> 
        
          <%= text_field_tag 'gossip_content'%>
          <%= label_tag 'Dis nous tout' %>
        
        <br /> <br />
        <%= submit_tag "Valider", class: 'btn btn-primary btn-lg btn-submit'  %>
      <% end %>
    </div>
  </body>
</html>

app/views/gossip/show.html.erb
<div class="container">
      
     <%= flash_messages %>

     <%= yield %>
   </div><!-- /container -->




<p> L'auteur s'appelle : <%= @my_gossip.user.first_name %>  </p>




<p> Le titre de ce gossip est : <%= @my_gossip.title %> </p>

<p> Le contenu du gossip est : <%= @my_gossip.content %> </p>

<p> La ville de l'auteur : <%= @my_city.name %> </p>


<%= link_to "Lien vers la ville de l'auteur", city_path(@my_city.id) %>

<p> Il a été créé le : <%= @my_gossip.created_at %> </p>


<% if current_user.id == @my_gossip.user.id%>

<button type="button" class="btn btn-dark" style="margin-bottom:10px;">

<a <%= link_to 'Clique ici pour éditer',edit_gossip_path(@my_gossip.id) %> </a>

</button>

<%end%>

<div>

<%= form_tag url_for(action: 'destroy'), method: "DELETE" do %>
    <%= submit_tag "DESTRUCTION", class: 'btn btn-danger btn-lg btn-submit col-4'  %>
      <% end %>
      </div>






<%= render 'comment/comments' %>