config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 
 
 resources:team
 
 resources:author
 
 resources:contact

 resources:city

 resources:user

 resources :sessions, only: [:new, :create, :destroy]

 resources :like 

 resources :gossip do
  resources :like
  resources :comment
  get :display
 end
 
  

get '/', to: 'gossip#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content,
	  presence: true
    belongs_to :user
    belongs_to :gossip		
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title, 
	  presence: true,
	  length: { minimum: 3, wrong_length: "3 to 14 characters is allowed" }
	validates :content,
	  presence: true

	belongs_to :user
	has_many :join_tag_gossips
	has_many :tags, through: :join_tag_gossips
	has_many :comments
	has_many :likes


end

app/models/join_pm.rb
class JoinPm < ApplicationRecord
	belongs_to :user
	belongs_to :private_message
end

app/models/join_tag_gossip.rb
class JoinTagGossip < ApplicationRecord
	belongs_to :tag 
	belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :user
    has_many :join_pms
    
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_tag_gossips
	has_many :gossips, through: :join_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
	validates :email,
      presence: true, #tjr rempli
      uniqueness: true,  #unique
      format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" } 
    validates :first_name,
      presence: true
    validates :last_name,
      presence: true
    validates :description,
      presence: true
    validates :age,
      presence: true,
	  numericality: { only_integer: true, greater_than_or_equal_to: 1}
    

	belongs_to :city
	has_many :gossips
	has_many :private_messages
	has_many :join_pms
	has_many :comments
	has_many :likes
	has_secure_password
 
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper

    def log_in(user)
        session[:user_id] = user.id
      end
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%= link_to "The Gossip Projet", gossip_index_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "Home", gossip_index_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Team", team_index_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Contact", contact_index_path %></a>
        
        <% if current_user %>

        <li class="nav-item">
        <a class="nav-link" <%= link_to "Se déconnecter", session_path(session.id), method: :delete %></a>


        <%else%>

        <li class="nav-item">
        <a class="nav-link" <%= link_to "S'inscrire", new_user_path %></a>
        
        <li class="nav-item">
        <a class="nav-link" <%= link_to "Se connecter", new_session_path %></a>

        <% end %> 


        
      </li> 
    </ul>
  </div>
</nav>
  <head>
    <title>YoloApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>